### ISSUE TITLE
"Invalid toxme domain supplied"

### ISSUE THREAD

**Issue by vi** [Antox/Antox#193]
when trying to input something in text field and press green "Register" button.

For version 0.23.71 from F-Droid.

Also F-Droid offsers only one nightly version to install. I expect multiple versions (e.g. N previous nightlies) to be available.

**Comment by subliun** [comment]
fixed

**Comment by xylo** [comment]
I still get this error message with version 0.23.343 that I downloaded today via the f-droid repository.
The message appears when I enter any profile name and press the register button.

I'm using Android 6.0.1.

**Comment by subliun** [comment]
@GrayHatter do you know anything about this?

**Comment by ProMcTagonist** [comment]
@xylo 

Thanks for reporting this issue.

Unfortunately, @subliun runs the website toxme.io. He took it down the other day because he was upset at another developer. He's proven himself incapable of conducting himself in a professional manner, and unworthy of further involvement with the project.

We're working to resolve this problem, and we apologize for any inconvenience you may have experienced.

**Comment by xylo** [comment]
Well, that's a pity.
But thhanks for the information, @ProMcTagonist. I hope you can resolve the issue somehow.

**Comment by GrayHatter** [comment]
@subliun actually, I do know something about it. You the admin of toxme.io turned it off on a while after you lost op status on a tox gaming irc channel because you 1) didn't play with us anymore 2) left tox after your little hissy fit, and 3) were trolling the channel, and begging for a what.cd invite.

Then when you found out you lost ops, (days later) 

```
<subliun> grayhatter: did you get gentoo to de-op me?
<subliun> also, give me my voice back
<grayhatter> yes
<subliun> also, https://toxme.io has reached 8500 users! \o/
<subliun> right, give me my voice back and give me my op back
<oranges> no
<subliun> yes
<grayhatter> ops are for devs
<grayhatter> look
<oranges> tox on mobile phones is dead
<grayhatter> even oranges dosent' have ops
<grayhatter> and hes' not complaining
<grayhatter> and he memes harder than anyone
<subliun> hexaflouride isn't a dev
<grayhatter> https://github.com/hexafluoride/Detox
<subliun> you are literally zero-one aren't you
<oranges> zero-one quit
<oranges> I'm in charge now
<grayhatter> I'm zero-one without the trust issues
<subliun> zero-one quit before he showed up
<subliun> now, I'd really like my op back
<subliun> and my voice
<grayhatter> I'd really like my dog to be sleeping at my feet
<grayhatter> life's not fair
<stal> :(
<subliun> sigh
<grayhatter> get used to it now
<stal> all dogs go to heaven grayhatter
<subliun> I'll make all toxme dns requests redirect to a service telling people to install qtox
<subliun> that'll be fun
<subliun> uTox never needed users anyway
<grayhatter> you can do what ever you'd like mate
<grayhatter> but keep it up and see how benevolent I'm feeling tonight 
<subliun> I'm a very fickle person grayhatter
<grayhatter> you think I'm vindictive and arbitrary now...
<subliun> https://toxme.io/
<subliun> if anyone wants to know why toxme is down, ask grayhatter
<zero-ghost> this is how grown up act weeeeeee
<stal> it is a good thing i don't have ops in this channel
<grayhatter> lol
<grayhatter> sure you don't
<subliun> why are you here stal
<stal> good question subliun
<subliun> I'm here because I booted into linux by mistake
<subliun> I should really remove this partition
<subliun> grayhatter: shoot me an email when I'm op in foss gaming again and I'll bring toxme back up
<grayhatter> subliun get fucked
<subliun> if it's more than a month I see no reason to keep paying for that box
<grayhatter> I don't negotiate with terrorists 
<subliun> bye
<stal> rip
<grayhatter> fucking child
<stal> see everyone
<stal> this is why we wanted a distributed solution
<grayhatter> lol
<stal> but you wanted conveniece
```

log edited to remove some noise from other users no relevant to this exchange.

**Comment by nurupo** [comment]
>He's proven himself incapable of conducting himself in a professional manner, and unworthy of further involvement with the project.

He actually hasn't been involved with the project for months now, he declared that he is leaving for personal reasons sometime in January. @wiiaam has took over the Antox development in his stead.

Anyone is free to host a service like toxme.io, it's open source. Also, I don't see how it is a threat to the project/developers if someone hosting their own instance of the toxme decides to shut it down. It's not like the tox project/developers are responsible for toxme services someone somewhere runs. It's like me saying "I'm shutting down my IRC network until you give me a sit in the IRCv3 protocol committee". Why should IRCv3 committee people even care about someone shutting down their own IRC network? If @subliun doesn't want to run his service anymore then he is free to shut it down, no one is forcing him to run it, he was doing it voluntary, out of kindness of his heart.

The whole threat deal and the silliness of the reason for shutting the service down just shows me that subliun is probably not someone whose service I would use.

**Comment by subliun** [comment]
>subliun is probably not someone whose service I would use.
I agree and this is something I have been saying from the beginning. If someone trustworthy in The Tox Project sets up their own toxme instance I would be happy to redirect toxme.io and hand over the user database. Otherwise I'd just like to be unquieted in the games channel please.

**Comment by GrayHatter** [comment]
that's a lie, on the 26th stal and I both offered to pay you to turn it over to stal

```
[20:15:02] <subliun> I'll keep it up for 5 years or for a year after the last new feature added to toxcore
[20:15:09] * subliun shuts down toxme instantly
[20:15:16] <subliun> ;^)
[20:15:32] <stal> i'll pay you $1
[20:15:34] <stal> for toxme
[20:15:43] <grayhatter> I'll chip in 10
[20:15:48] <subliun> 8000 users is worth more than one dollar
[20:15:52] <stal> that's $1 cad
[20:15:52] <subliun> will you keep it up?
[20:15:53] <grayhatter> that's 11$ to transfer everything to stal right now
[20:16:23] <subliun> actually no
[20:16:29] <subliun> you'll add dns again won't you
[20:16:39] <grayhatter> me? yes
[20:16:40] <subliun> the deal is off
[20:16:44] <stal> i'll give you $0.50 cad to transfer everything to the garbage
[20:16:46] <grayhatter> but you'll transfer it to stal
[20:17:01] <grayhatter> stal probably wont
[20:17:08] <grayhatter> actually I probably won't too
[20:17:13] <grayhatter> DNS should die
[20:17:15] <subliun> stal: delete toxme right now for 50 cents?
[20:17:20] <stal> i'll just rewrite toxme using tornado
[20:17:21] <subliun> tempting
```

**Comment by JFreegman** [comment]
I can't even comprehend the mindset of someone who would shut down a service that thousands of people rely on over losing OP in an off-topic IRC channel. I hope your reputation doesn't mean much to you @subliun, because this isn't going to be something that people forget.

**Comment by subliun** [comment]
@GrayHatter stal is not someone trustworthy in the Tox Project

**Comment by JFreegman** [comment]
@subliun First of all, stal has never done anything that would make me question his trustworthiness. Second of all, you don't get to pull something like this and then pretend that you actually care about the project or its users. It's one or the other.

**Comment by GrayHatter** [comment]
That doesn't make sense. stal WROTE the program you're using. At a point in time where there was no other OSX tox client ported µTox to OSX, and currently maintains more than a few services for tox. He's also volunteered for more things that I can count. that's in addition to what @JFreegman said

Plus he's mature enough not to hold >8k users hostage for ops in an IRC game channel, of which you don't play any games in.

**Comment by subliun** [comment]
>which you don't play any games in

You never invite me :'(

**Comment by GrayHatter** [comment]
also a lie

**Comment by stal888** [comment]
If you give me toxme I can save you the trouble of binning it.

**Comment by wiiaam** [comment]
rip toxme

**Comment by subliun** [comment]
toxme.io is back by the way. It'll stay up until the domain expires (or something else happens) and then @Zero-One will buy it off me.

**Comment by wiiaam** [comment]
@subliun are you going to transfer the db or is toxme going to be wiped

**Comment by subliun** [comment]
Transfer the db
