### ISSUE TITLE
Crash if client is unable to download nodelist

### ISSUE THREAD

**Issue by h1z1** [Antox/Antox#315]
Been trying to find out why Antox crashes on an S7 (Android, 64bit arm) - it may not be permissions.  If the client is unable to download the nodelist, it also crashes.  From what I gather the code assumes if it cannot _update_ the list, it tries whatever existing file is there.  I couldn't find any tests to verify the file at all, not even so much as a checksum?   The host itself resolves to one IP.  

To reproduce:
- firewall / block access to the nodelist server
- install Antox, change permissions
- run client, type anything and hit register, client crashes

Clear applications data, to retest.  No need to reinstall client

Stack trace is rather long, in essence:

07-15 02:54:50.429 29768-29768/chat.tox.antox D/Antox: Tox disconnected. Scheduled reconnection every 60 seconds
07-15 02:55:50.429 29768-29802/chat.tox.antox D/Antox: Reconnecting
07-15 02:55:50.429 29768-29802/chat.tox.antox D/Bootstrap: Nodefile does not exist, fetching new one
07-15 02:55:50.429 29768-29802/chat.tox.antox D/UpdateDhtNodes: in observable
07-15 02:55:50.429 29768-29802/chat.tox.antox D/UpdateDhtNodes: about to readJsonFromUrl
07-15 02:55:50.429 29768-29802/chat.tox.antox I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-15 02:55:50.429 29768-29802/chat.tox.antox I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-15 02:55:50.459 29768-29802/chat.tox.antox E/UpdateDhtNodes: couldn't reach Nodefile URL
07-15 02:55:50.459 29768-29802/chat.tox.antox E/Antox: JsonReader readJsonFromFile error
                                                       java.io.FileNotFoundException: /data/user/0/chat.tox.antox/files/Nodefile.json: open failed: ENOENT (No such file or directory)
                                                           at libcore.io.IoBridge.open(IoBridge.java:452)
                                                           at java.io.FileInputStream.<init>(FileInputStream.java:76)
                                                           at scala.io.Source$.fromFile(Source.scala:91)

It will also crash if one of those nodes is unavailable.  I hit this because my phones are completely isolated from everything.  Android is _extremely_ call home happy between Samsung's own logging crap, to Google and swiftkey.  It amazes me people use Android at all.

**Comment by licaon-kter** [comment]
Still an issue on 0.25.465, strange because I was under the impression this was fixed.

Log: https://gist.github.com/3b11239443b077995246d654490dd5d8

**Comment by zoff99** [comment]
@licaon-kter its fixed in this unofficial development version:

https://circleci.com/api/v1/project/zoff99/Antox/latest/artifacts/0/$CIRCLE_ARTIFACTS/Antox.apk?filter=successful&branch=zoff99%2FAntox_v0.25.1

**Comment by wetubeyou** [comment]
Still crash on latest FDroid version.
Log = https://gist.github.com/wetubeyou/e08c6dc8365985bfa32852936f07ca38

**Comment by zoff99** [comment]
try my version from the link above.

**Comment by wetubeyou** [comment]
@zoff99 It's not official, and hosted in outside github. I'll wait for official update.

**Comment by wetubeyou** [comment]
Why they can't post it to FDroid?

**Comment by licaon-kter** [comment]
You mean in the Tox repo or the official F-Droid repo? 
The answers are: this build is unofficial and see #341

**Comment by wetubeyou** [comment]
@licaon-kter
Tox repo. I downloaded Antox from FDroid app(which include tox repo).

**Comment by subliun** [comment]
Fixed hopefully
We all have dreams, and mine is that this issue is actually fixed
Please tell me if it isn't and I'll reopen this and fix it
